title: Rudramani Singha
email: rgs2151@columbia.edu
author: Rudramani Singha
description: >-
  Hey there! I'm a researcher based in New York City. 
  I build probabilistic models and reverse engineer the brain.
baseurl: ""
url: "https://singha.io"
google_analytics: G-XWEJZKE72S

# Build settings
plugins: []

scss:
  scss_dir: _sass
  style: compressed
