title: Rudramani Singha
email: rgs2151@columbia.edu
author: Rudramani Singha
description: >-
  Hey there! I build probabilistic models and reverse engineer the brain.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://singha.io" # the base hostname & protocol for your site
google_analytics: G-XWEJZKE72S

# Build settings
plugins: []

scss:
  scss_dir: _sass
  style: compressed
