name: Fast Jekyll Build & Deploy

on:
  push:
    branches: [ "master" ]

# Cancel old builds when new push happens  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build Jekyll (fast mode)
        run: |
          bundle exec jekyll build \
            --baseurl "${{ steps.pages.outputs.base_path }}" \
            --incremental \
            --quiet
        env:
          JEKYLL_ENV: production

      - name: Upload & Deploy
        uses: actions/upload-pages-artifact@v3
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4
